### ISSUE TITLE
load ETL5

### ISSUE THREAD

**Issue by amanotaiga** [amanotaiga/Tensorflow_CNN#2]
Could unpack ETL5 now.,but if I put things to array,it would show error message.

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "<stdin>", line 9, in store_array
>   File "<stdin>", line 5, in read_record_ETL5C
> TypeError: can only concatenate list (not "tuple") to list

```
def read_record_ETL5C(f):
    r = f.readlist('int:72,int:12,6*uint:4,pad:12,int:90,pad:1008,bytes:2736') 
    iF = Image.frombytes('F', (72,76), r[9], 'bit', 4)
    iL = iF.convert('P')
    return r + (iL,)

def store_array():
    filename = 'ETL5C'
    f = bitstring.ConstBitStream(filename=filename)
    f.pos = 0 * 6 * 3936
    ary = np.zeros([51, 212, 76, 72], dtype=np.uint8)
    for j in range(51):
        moji = 0
        for i in range(212):
            r = read_record_ETL5C(f)
            ary[j,moji] = np.array(r[-1])
            moji += 1
    np.savez_compressed("ETL5C_data.npz", ary)
```

And if I  write in this way `return tuple(r) + (iL,)`
It could be run but the result would be wrong(3% accuracy) .
And the dataset looks unclear,I'm not sure if I unpack it wrong.(ETL7 8 is fine)
![etl5_image](https://cloud.githubusercontent.com/assets/18046528/19805928/5e747e54-9d52-11e6-83b4-ae2575eb1429.jpg)

**Comment by caranha** [comment]
The difference is very regular (you get a full circle after every 600 elements), so I think your offset is probably wrong.
